spring:
  datasource:
    url: jdbc:mysql://172.18.161.171/burying?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: burying_java
    password: 6tVad2BGd6vuRp7i
    driverClassName: com.mysql.cj.jdbc.Driver
    xyDataSource:
      jdbc-url: jdbc:mysql://172.18.161.171/burying?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
      username: burying_java
      password: 6tVad2BGd6vuRp7i
      driver-class-name: com.mysql.cj.jdbc.Driver
#    stepsDataSource:
#      jdbc-url: jdbc:mysql://localhost:3306/point_test2?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
#      username: root
#      password:
#      driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 172.18.161.166
    port: 6379
    password: e8cFnj3CoWZdUFyXg8Dkv9Vp66c=
    database: 4
    timeout: 30000
  session:
    store-type: redis

  rabbitmq:
    #addresses: 47.112.141.18
    addresses: 172.18.161.169
    username: xiyou
    port: 5672
    password: REl1QCkkvpGICzSo

  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      username: bpjava
      password: taLXW6fLg0kviUwp8iYABWHTvpZ9pzQk
      database: bp
      uri: mongodb://172.18.161.174:27017